site_name: MR2 manual
theme:
  name: material
  icon:
    logo: material/book-open-blank-variant
  features:
    - navigation.instant
    - navigation.footer
    # - toc.integrate
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search:
      lang: en
extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dobicinaitis/toyota-mr2-repair-manual
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg